/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './blog/posts.component.ngfactory';
import * as i3 from '../../../../src/app/blog/posts.component';
import * as i4 from '@angular/platform-browser';
import * as i5 from '../../../../src/app/app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-posts',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_PostsComponent_0,i2.RenderType_PostsComponent)),
      i1.ɵdid(114688,(null as any),0,i3.PostsComponent,[i4.Meta,i4.Title],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i5.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i5.AppComponent> = i1.ɵccf('app-root',
    i5.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWlsYW4vRGVza3RvcC9qYWluQGFsZ293b3Jrcy90ZXN0L0FuZ3VsYXItU0VPLWZyaWVuZGx5LWV4YW1wbGUtbWFzdGVyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21pbGFuL0Rlc2t0b3AvamFpbkBhbGdvd29ya3MvdGVzdC9Bbmd1bGFyLVNFTy1mcmllbmRseS1leGFtcGxlLW1hc3Rlci9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL21pbGFuL0Rlc2t0b3AvamFpbkBhbGdvd29ya3MvdGVzdC9Bbmd1bGFyLVNFTy1mcmllbmRseS1leGFtcGxlLW1hc3Rlci9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvbWlsYW4vRGVza3RvcC9qYWluQGFsZ293b3Jrcy90ZXN0L0FuZ3VsYXItU0VPLWZyaWVuZGx5LWV4YW1wbGUtbWFzdGVyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YXBwLXBvc3RzPjwvYXBwLXBvc3RzPlxuIiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7YUFBQTtVQUFBLGVBQXVCO0lBQXZCOzs7O29CQ0FBO01BQUE7YUFBQTs7OzsifQ==
