/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWlsYW4vRGVza3RvcC9qYWluQGFsZ293b3Jrcy90ZXN0L0FuZ3VsYXItU0VPLWZyaWVuZGx5LWV4YW1wbGUtbWFzdGVyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvbWlsYW4vRGVza3RvcC9qYWluQGFsZ293b3Jrcy90ZXN0L0FuZ3VsYXItU0VPLWZyaWVuZGx5LWV4YW1wbGUtbWFzdGVyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
