/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWlsYW4vRGVza3RvcC9qYWluQGFsZ293b3Jrcy90ZXN0L0FuZ3VsYXItU0VPLWZyaWVuZGx5LWV4YW1wbGUtbWFzdGVyL3NyYy9hcHAvYmxvZy9wb3N0cy5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21pbGFuL0Rlc2t0b3AvamFpbkBhbGdvd29ya3MvdGVzdC9Bbmd1bGFyLVNFTy1mcmllbmRseS1leGFtcGxlLW1hc3Rlci9zcmMvYXBwL2Jsb2cvcG9zdHMuY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
