/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './posts.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from '../../../../../src/app/blog/posts.component';
import * as i4 from '@angular/platform-browser';
const styles_PostsComponent:any[] = [i0.styles];
export const RenderType_PostsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PostsComponent,data:{}});
function View_PostsComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'li',[['class',
      'list-group-item']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n                '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),1,'h4',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['',''])),(_l()(),i1.ɵted((null as any),['\n            ']))],(null as any),
      (_ck,_v) => {
        const currVal_0:any = _v.context.$implicit.title;
        _ck(_v,3,0,currVal_0);
      });
}
export function View_PostsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'jumbotron']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['Blogist'])),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['This is the best resource for the best web development posts.'])),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),10,'div',[['class','row']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),7,'div',[['class',
          'col-xs-12 col-md-12']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),4,'ul',[['class','list-group']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n            '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),
          1,(null as any),View_PostsComponent_1)),i1.ɵdid(802816,(null as any),0,i2.NgForOf,
          [i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,'ngForOf']},
          (null as any)),(_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i3.PostsComponent = _v.component;
    const currVal_0:any = _co.posts;
    _ck(_v,16,0,currVal_0);
  },(null as any));
}
export function View_PostsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-posts',([] as any[]),
      (null as any),(null as any),(null as any),View_PostsComponent_0,RenderType_PostsComponent)),
      i1.ɵdid(114688,(null as any),0,i3.PostsComponent,[i4.Meta,i4.Title],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PostsComponentNgFactory:i1.ComponentFactory<i3.PostsComponent> = i1.ɵccf('app-posts',
    i3.PostsComponent,View_PostsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWlsYW4vRGVza3RvcC9qYWluQGFsZ293b3Jrcy90ZXN0L0FuZ3VsYXItU0VPLWZyaWVuZGx5LWV4YW1wbGUtbWFzdGVyL3NyYy9hcHAvYmxvZy9wb3N0cy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9taWxhbi9EZXNrdG9wL2phaW5AYWxnb3dvcmtzL3Rlc3QvQW5ndWxhci1TRU8tZnJpZW5kbHktZXhhbXBsZS1tYXN0ZXIvc3JjL2FwcC9ibG9nL3Bvc3RzLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvbWlsYW4vRGVza3RvcC9qYWluQGFsZ293b3Jrcy90ZXN0L0FuZ3VsYXItU0VPLWZyaWVuZGx5LWV4YW1wbGUtbWFzdGVyL3NyYy9hcHAvYmxvZy9wb3N0cy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvbWlsYW4vRGVza3RvcC9qYWluQGFsZ293b3Jrcy90ZXN0L0FuZ3VsYXItU0VPLWZyaWVuZGx5LWV4YW1wbGUtbWFzdGVyL3NyYy9hcHAvYmxvZy9wb3N0cy5jb21wb25lbnQudHMuUG9zdHNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwianVtYm90cm9uXCI+XG4gICAgPGgxPkJsb2dpc3Q8L2gxPlxuICAgIDxwPlRoaXMgaXMgdGhlIGJlc3QgcmVzb3VyY2UgZm9yIHRoZSBiZXN0IHdlYiBkZXZlbG9wbWVudCBwb3N0cy48L3A+XG48L2Rpdj5cbjxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICA8ZGl2IGNsYXNzPVwiY29sLXhzLTEyIGNvbC1tZC0xMlwiPlxuICAgICAgICA8dWwgY2xhc3M9XCJsaXN0LWdyb3VwXCI+XG4gICAgICAgICAgICA8bGkgY2xhc3M9XCJsaXN0LWdyb3VwLWl0ZW1cIiAqbmdGb3I9XCJsZXQgcG9zdCBvZiBwb3N0c1wiPlxuICAgICAgICAgICAgICAgIDxoND57e3Bvc3QudGl0bGV9fTwvaDQ+XG4gICAgICAgICAgICA8L2xpPlxuICAgICAgICA8L3VsPlxuICAgIDwvZGl2PlxuPC9kaXY+XG4iLCI8YXBwLXBvc3RzPjwvYXBwLXBvc3RzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ09ZO01BQUE7TUFBQSxnQkFBdUQsdURBQ25EO2FBQUE7VUFBQSw0Q0FBSTtNQUFBLFVBQW1COztRQUFuQjtRQUFBOzs7O29CQVJwQjtNQUFBO01BQXVCLDJDQUNuQjtVQUFBO1VBQUEsZ0JBQUksNENBQVk7VUFBQSxhQUNoQjtVQUFBO01BQUc7TUFBaUUsdUNBQ2xFO01BQ047VUFBQSwwREFBaUI7VUFBQSxhQUNiO1VBQUE7VUFBQSxnQkFBaUMsK0NBQzdCO1VBQUE7VUFBQSwwREFBdUI7VUFBQSxxQkFDbkI7VUFBQSwrQ0FBQTtVQUFBO1VBQUEsZUFFSywrQ0FDSjtVQUFBLGFBQ0gsdUNBQ0o7VUFBQTs7SUFMa0M7SUFBNUIsWUFBNEIsU0FBNUI7Ozs7b0JDUFo7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
